### ISSUE TITLE
Update Docker image

### ISSUE THREAD

**Issue by chrisanthropic** [chrisanthropic/Open-Publisher#14]
I wrote the initial Dockerfile over a year ago. Time to revisit it and work to make the container size as small as possible.

**Comment by gitfineon** [comment]
Hey, your project description promises a cool project.
I tried to test it but 
```
$ sudo docker run -v $PWD/input:/Open-Publisher/Source -v $PWD/output:/Open-Publisher/Books -it open-publisher rake build --trace
rake aborted!
Don't know how to build task 'build'
/usr/local/lib/ruby/2.1.0/rake/task_manager.rb:49:in `[]'
/usr/local/lib/ruby/2.1.0/rake/application.rb:148:in `invoke_task'
/usr/local/lib/ruby/2.1.0/rake/application.rb:106:in `block (2 levels) in top_level'
/usr/local/lib/ruby/2.1.0/rake/application.rb:106:in `each'
/usr/local/lib/ruby/2.1.0/rake/application.rb:106:in `block in top_level'
/usr/local/lib/ruby/2.1.0/rake/application.rb:115:in `run_with_threads'
/usr/local/lib/ruby/2.1.0/rake/application.rb:100:in `top_level'
/usr/local/lib/ruby/2.1.0/rake/application.rb:78:in `block in run'
/usr/local/lib/ruby/2.1.0/rake/application.rb:165:in `standard_exception_handling'
/usr/local/lib/ruby/2.1.0/rake/application.rb:75:in `run'
/usr/local/bin/rake:33:in `<main>'
```

I did the following steps in zsh shell:
``` zsh
$ git clone https://github.com/chrisanthropic/Open-Publisher.git
$ cd Open-Publisher
$ sudo docker build -t open-publisher .
$ sudo docker run -v $PWD/input:/Open-Publisher/Source -it open-publisher rake skel
$ sudo docker run -v $PWD/input:/Open-Publisher/Source -v $PWD/output:/Open-Publisher/Books -it open-publisher rake 'all[all]'

...
Info(prcgen):I1036: Mobi file built successfully

$ evince output/Example/Example-5x8-print.pdf 
```
The Example worked fine, but creating a new book fails  ... can you help?

**Comment by Letme** [comment]
Sorry for late reply, but I am just joining the fan club. The solution is to call `create` instead of `build`. Wiki needs updating, but I somehow cannot do it.

```
sudo docker run -v $PWD/input:/Open-Publisher/Source -v $PWD/output:/Open-Publisher/Books -it  ctarwater/open-publisher rake create
```

Its a simple fix in docs.
